### Добавить в список продукт Orange

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Orange",
  "quantity": 60,
  "cost": 150.0
}

### Добавить в список продукт Apple

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Apple",
  "quantity": 500,
  "cost": 70.0
}

### Добавить в список продукт Kinder

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Kinder",
  "quantity": 1000,
  "cost": 91.0
}
