### Добавить в список продукт Orange

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Orange",
  "quantity": 60,
  "cost": 150.0
}

### Добавить в список продукт Appel

POST http://localhost:8080/products
Content-Type: application/json

{
  "name": "Appel",
  "quantity": 500,
  "cost": 70.0
}

### Получить список продуктов

GET http://localhost:8080/products

### Получить продукт по id = 1

GET http://localhost:8080/products/{{id}}

### Обновить данные продукта по id = 1

PUT http://localhost:8080/products/{{id}}
Content-Type: application/json

{
  "name": "Oreo",
  "quantity": 111,
  "cost": 130.0
}

### Удалить продукт по id = 1

DELETE http://localhost:8080/products/{{id}}
